### ISSUE TITLE
LSM9DS0 graphical interface

### ISSUE THREAD

**Issue by chiccodoro** [sparkfun/LSM9DS0_Breakout#13]
Hi Jim,
I am using your sample code for the IMU with an arduino micro.
I would like to collect the data in real time and plot it on a chart instead of using the serial monitor. I was wondering if you have any suggestion which graphical user interface I can use. In addition, do you think it is possible with such device to compute the displacement in the mm range?
I hope you can help.
Regards,
Francesco.

**Comment by jimblom** [comment]
Hi Francesco,

If you have the Arduino hooked up to a computer, I'd recommend trying to use [Processing](https://processing.org/) to graph the data. The Arduino can send the IMU's data to the computer over the serial port, which the processing sketch can then interpret and plot.

I don't have any example code for this application, but we've do have a [Connecting Arduino to Processing tutorial](https://learn.sparkfun.com/tutorials/connecting-arduino-to-processing) that may help you get started.

**Comment by chiccodoro** [comment]
Thank you, Jim!
I am going to do it :-)
