### ISSUE TITLE
Usage for ESP8266

### ISSUE THREAD

**Issue by HackershubNL** [sparkfun/LSM9DS0_Breakout#15]
This library doesn't work out of the box with the ESP8266.
It has to do with the initialization of I2C. To make it work, change line 642 in [SFE_LSM9DS0.cpp
](https://github.com/sparkfun/LSM9DS0_Breakout/blob/master/Libraries/Arduino/src/SFE_LSM9DS0.cpp)
from

```
void LSM9DS0::initI2C()
{
    Wire.begin();   // Initialize I2C library
}
```

to

```
void LSM9DS0::initI2C()
{
    Wire.begin(2, 14);  // Initialize I2C library
    Wire.setClock(100000);
}
```

**Comment by ToniCorinne** [comment]
Hi @HackershubNL - we're currently looking at this issue for a few of our boards. You can reference our conversation about this on the BMP180 repo [here](https://github.com/sparkfun/BMP180_Breakout_Arduino_Library/pull/1#issuecomment-194607324).

**Comment by santaimpersonator** [comment]
Closing in reference to the issue linked above. Problem was with the `Wire` library for the ESP32 and has since been resolved.
