### ISSUE TITLE
LSM9DS0 sensor fusion and AHRS sketch

### ISSUE THREAD

**Issue by kriswiner** [sparkfun/LSM9DS0_Breakout#2]
Hi Jim,

I modified your sketches and libraries to implement two open-source 9 DoF sensor fusion algorithms using quaternion representation for the absolute orientation of the sensor relative to the fixed Earth frame.  I can't quite figure out GitHub so I don't know how to issue a formal pull request. If you are interested in adding the sketch and modified libraries to the Sparkfun repository you are welcome to them. You will find them at kriswiner/LSM9SD0.

I do have one suggestion: can we get the next version of the breakout board in a smaller footprint, say, pins on two sides so the footprint is more squarish than rectangular. This will save limited space on a proto-board!

Thanks for an easy to use and understand library.

Kris

**Comment by bsnayak** [comment]
Hi Kris,

Thank you very much for your contributions!
Does this code available on kriswiner/LSM9DS0 performs on Arduino as well ? In this case, Which Pin configuration needs to be changed here with respect to Arduino 

Reference : 
         LSM9DS0 Micro ----- Teensy 3.1
     SCL --------------pin 29   SCL
     SDA --------------pin 30   SDA
     VDD ------------- pin 34   3V3
     GND ------------- pin 23   GND
         SDO --------------pin 31  (change address of LSM9DS0)  
         DRDYG-------------pin 24  (gyro data ready interrupt)
         INTG--------------pin 25  (gyro Interrupt)
         DENG--------------pin 26  (allows syncing of gyro and accelerometer)
         INTXM1------------pin 27  (accelerometer data ready interrupt)
         INTXM2------------pin 32  (magnetometer data ready interrupt)
Regards

Nayak

**Comment by kriswiner** [comment]
Hi Nayak,

On Arduino you would connect SDA to 4, SCL to 5, power and GND to 3V3 (the
sensor is NOT 5 V tolerant, so if you use an Arduino UNO you need a logic
level translator). If you want to use the interrupts (any digital Arduini
pin will do)then you need a logic level translator too for 5 V, not for a
3V3 Arduino 8 MHz Pro Mini. Yes, the device will work with an 8 MHz Pro
Mini, that's what I used to use until I discovered the Teensy. The latest
LSM9DS0 Micro Add-On can work with an Arduino on a breadboard but it is
really designed to be soldered on the back of a Teensy. I have another
LSM9DS0 "Mini" version with through holes that would be better for
breadboarding, it comes with an MD5611 pressure sensor. If you want one of
these, I can assemble them for you. I just usually don't keep these in
stock.

Kris
Pesky Products

-----Original Message-----
